### PR TITLE
Display time remaining (upload)

### PR DESCRIPTION
**Pull request by chrisidefix**
Addressing request in issue #69 to display remaining time to complete upload (at current average upload speed). Display structured to only display seconds, when remaining time is below 1 min. If remaining time is higher, we either display hours and minutes or just the remaining minutes.

Also added some code to flush the command-line to avoid ugly strings to remain visible.

### CODE REVIEW

**Comment by yadayada** [comment]
This messes up every log message for me. Secondly, the progress line should fit into a standard console which has a width of 80.

**Comment by chrisidefix** [comment]
Would be interesting to know what OS and SHELL you are running on, maybe this only works in bash and/or under OS X? We could also just reduce the number of elements in the `[####          ]` section to show progress - I reckon 10 `#` are enough?

**Comment by yadayada** [comment]
I'm using Debian testing and zsh, but I'm not sure it would matter.
If there is no carriage return at the end of the progress indicator line, the log messages should be appended to it rather than overwriting it (this happens for me).
Also, the (absence of) spaces between numbers and units of measurement should be consistent on the whole line.
If the remaining space is just enough for a progress bar 10 characters wide, maybe it's best just to omit it and put in more useful information like curl does...

**Comment by yadayada** [comment]
I merged the extended version of this by @resipsa2917.

**Pull request closed without merging**
