### PR TITLE
Allow commands like du -sk to report the correct file sizes.

### PR DESCRIPTION
**Pull request by docbill**
Updated the stat(2) returns to include number of blocks and block size.

### CODE REVIEW

**Comment by docbill** [comment]
This latest commit extends on the mtime storage xattr trick to store uid, gid, and mode.   That is sufficient so rsync now works with the --inplace flag.   Non-inplace rsync copies are still failing in extremely odd ways...

**Comment by docbill** [comment]
Any progress in deciding if you will apply this pull request?   The most important part to me is the xattr fix.  But getting the rest of the metadata correct is very useful as well.   I don't have a good workaround to somehow store this information separately from the files when doing a backup, and I imagine others hit the issue as well.

**Comment by yadayada** [comment]
I use the dev branch mainly as a scratchpad, so I'm uncertain why you would want to merge into dev. Also, your second commit depends on #374, and I'm still undecided what to do about that.

**Comment by docbill** [comment]
Oh, why dev that is easy.   You mentioned it in one of the other issues as solving a problem I was seeing.   Sure enough it did, and besides the tmp space issue it has been much more stable.  Most developers develop in a branch and pushed to their master when they are ready.   So it made sense to put the patch there.   It would not really make sense to patch a branch I'm not using and would therefore be a completely untested fix.   However, if you want I can try and back port it.

**Comment by yadayada** [comment]
Thanks, @docbill. I merged the other PR and I think we can consider this one merged into @bgemmill's PR.

**Pull request closed without merging**
