### PR TITLE
#464 - Fixed missing files by preventing second cache drop.

### PR DESCRIPTION
**Pull request by ofir123**

### CODE REVIEW

**Comment by msh100** [comment]
Hey @ofir123 is this still holding well?

**Comment by msh100** [comment]
After a bit of testing, I am not convinced this is a working fix

**Comment by yadayada** [comment]
@msh100 Thanks for testing. I thought it was a bit odd.

**Comment by ofir123** [comment]
@msh100 what was the problem? 
I'm using this fix for about 2 months now, and it's holding well..

**Comment by msh100** [comment]
@ofir123 Looked the same as the original issue, nodes were not present in syncs

Honestly I didn't dig much into this, but first appearance is that this does nothing

**Comment by ofir123** [comment]
From what I experienced, Amazon's API was turning on the reset flag for certain nodes (no idea why).
But when ignoring it, everything works find and the nodes get synced..

**Comment by msh100** [comment]
Happy to retry. But I'm not convinced. 

I'll get back to you.

**Pull request closed without merging**
